config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                    Prefix Verb     URI Pattern                                                                              Controller#Action
#                      root GET      /                                                                                        pages#main
#                    logout GET      /logout(.:format)                                                                        pages#logout
#         apply_job_opening PUT      /job_openings/:id/apply(.:format)                                                        job_openings#apply
#              job_openings GET      /job_openings(.:format)                                                                  job_openings#index
#                           POST     /job_openings(.:format)                                                                  job_openings#create
#           new_job_opening GET      /job_openings/new(.:format)                                                              job_openings#new
#          edit_job_opening GET      /job_openings/:id/edit(.:format)                                                         job_openings#edit
#               job_opening GET      /job_openings/:id(.:format)                                                              job_openings#show
#                           PATCH    /job_openings/:id(.:format)                                                              job_openings#update
#                           PUT      /job_openings/:id(.:format)                                                              job_openings#update
#                           DELETE   /job_openings/:id(.:format)                                                              job_openings#destroy
#          login_applicants GET|POST /applicants/login(.:format)                                                              applicants#login
#                applicants GET      /applicants(.:format)                                                                    applicants#index
#                           POST     /applicants(.:format)                                                                    applicants#create
#             new_applicant GET      /applicants/new(.:format)                                                                applicants#new
#            edit_applicant GET      /applicants/:id/edit(.:format)                                                           applicants#edit
#                 applicant GET      /applicants/:id(.:format)                                                                applicants#show
#                           PATCH    /applicants/:id(.:format)                                                                applicants#update
#                           PUT      /applicants/:id(.:format)                                                                applicants#update
#                           DELETE   /applicants/:id(.:format)                                                                applicants#destroy
#           login_employers GET|POST /employers/login(.:format)                                                               employers#login
#                 employers GET      /employers(.:format)                                                                     employers#index
#                           POST     /employers(.:format)                                                                     employers#create
#              new_employer GET      /employers/new(.:format)                                                                 employers#new
#             edit_employer GET      /employers/:id/edit(.:format)                                                            employers#edit
#                  employer GET      /employers/:id(.:format)                                                                 employers#show
#                           PATCH    /employers/:id(.:format)                                                                 employers#update
#                           PUT      /employers/:id(.:format)                                                                 employers#update
#                           DELETE   /employers/:id(.:format)                                                                 employers#destroy
#        rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: 'pages#main'
  match 'logout', to: 'pages#logout', via: [:get]

  resources :job_openings do
    put :apply, on: :member
  end
  resources :applicants do
    match :login, on: :collection, via: %i[get post]
  end
  resources :employers do
    match :login, on: :collection, via: %i[get post]
  end
end

app/models/employer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: employers
#
#  id              :bigint(8)        not null, primary key
#  email           :citext           not null
#  password_digest :string
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_employers_on_email  (email) UNIQUE
#

class Employer < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true

  has_many :job_openings
end

app/controllers/employers_controller.rb
# frozen_string_literal: true

class EmployersController < ApplicationController
  before_action :set_employer, only: %i[show]
  skip_before_action :ensure_logged_in, only: %i[login new create]

  def login
    if request.method_symbol == :get
      @employer = Employer.new
    else
      @employer = Employer.find_by(email: employer_params[:email]).try(:authenticate, employer_params[:password])
      if @employer
        login_user(@employer)
        redirect_to @employer
      else
        redirect_to action: 'login'
      end
    end
  end

  def index
    @employers = Employer.all
  end

  def show; end

  def new
    @employer = Employer.new
  end

  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        login_user(@employer)

        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_employer
    @employer = Employer.find(params[:id])
  end

  def employer_params
    params.require(:employer).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/employers/_form.html.slim
= form_for @employer do |f|
  - if @employer.errors.any?
    #error_explanation.notification.is-danger
      h2 = "#{pluralize(@employer.errors.count, "error")} prohibited this employer from being saved:"
      ul
        - @employer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, class: 'label'
    = f.text_field :name, class: 'input'
  .field
    = f.label :email, class: 'label'
    = f.text_field :email, class: 'input'
  .field
    = f.label :password, class: 'label'
    = f.password_field :password, class: 'input'
  .field
    = f.label :password_confirmation, class: 'label'
    = f.password_field :password_confirmation, class: 'input'

  .actions = f.submit 'Register', class: 'button is-primary'

app/views/employers/login.html.slim
h1.title.is-1 Employer Login
.box
  = form_for @employer, url: login_employers_path do |f|
    .field
      = f.label :email, class: 'label'
      = f.text_field :email, class: 'input'
    .field
      = f.label :password, class: 'label'
      = f.password_field :password, class: 'input'

    .actions = f.submit 'Login', class: 'button is-primary'

= link_to 'Employer Registration', new_employer_path

app/views/employers/new.html.slim
h1 New employer registration

.box
  == render 'form'

= link_to 'Employer Login', login_employers_path

app/views/employers/show.html.slim
p#notice = notice

h2.title.is-2 = "#{@employer.name} Job openings"

.box
  table.table
    thead
      tr
        th(colspan=2) Job Listing
        th Applications
    tbody
    - @employer.job_openings.each do |job_opening|
      tr
        td(colspan=2) = job_opening.title
        td = job_opening.job_applications.count
      - job_opening.job_applications.each do |application|
        tr
          td
          td(colspan=2) = application.applicant.name
= link_to 'Post new listing', new_job_opening_path, class: 'button is-primary'